version : '3'
services :
  web:
    build : .
    container_name : srv-loopback
    links :
      - sql
    ports :
      - 80:80
      - 10501:10501
    
  sql:
    image : mysql:5.7
    container_name : srv-loopback-db
    ports : 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD : ApQm@2017!
      MYSQL_DATABASE : loopback-db
      MYSQL_USERNAME : loopusr
      MYSQL_PASSWORD : loopmdp
    volumes : 
      - ./sql:/docker-entrypoint.sql/
    
